GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1heElzQ29vbDc3NyIsImlkIjoiNmEzNmFhYWE2YWRhNDQ0ZjBjODljN2VjIiwiaWF0IjoxNzgxOTgyMzQ5fQ.Ogt8PN6KTrUUAWavb05rNw0y0-JUHyVp5WfYTflKJhs

{
    "title": "Title",
    "author": "Author",
    "url": "SomeURL",
    "likes": 13
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "MaxIsCool777",
    "name": "Max",
    "password": "123454321"

}
###
POST http://localhost:3003/api/login
Content-Type:  application/json

{
    "username": "MaxIsNOTCool",
    "password": "543212345"
}
###
POST http://localhost:3003/api/login
Content-Type:  application/json

{
    "username": "MaxIsCool777",
    "password": "123454321"
}
###
DELETE http://localhost:3003/api/blogs/6a36e8d95eb1026f5079350e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1heElzQ29vbDc3NyIsImlkIjoiNmEzNmFhYWE2YWRhNDQ0ZjBjODljN2VjIiwiaWF0IjoxNzgxOTgyMzQ5fQ.Ogt8PN6KTrUUAWavb05rNw0y0-JUHyVp5WfYTflKJhs
